### ISSUE TITLE
Cannot install via APT repository, 403 Forbidden

### ISSUE THREAD

**Issue by mlaurense** [newrelic/newrelic-php-agent#1057]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Trying to install NewRelic via APT using Ansible gives a 403 Forbidden response, from Cloudflare, Ray ID 934d2c554dc57271

## Steps to Reproduce

Relevant Ansible file
```
- name: Add NewRelic Signing Key
  apt_key:
    url: https://download.newrelic.com/548C16BF.gpg
    state: present
- name: Add NewRelic PPA
  apt_repository:
    repo: 'deb http://apt.newrelic.com/debian/ newrelic non-free'
    state: present
```

## Expected Behavior

Installed NewRelic

## Relevant Logs / Console output

```
env DEBIAN_FRONTEND=noninteractive apt-get update -y
E: Failed to fetch http://apt.newrelic.com/debian/dists/newrelic/InRelease  403  Forbidden [IP: 162.247.242.3 80]
E: The repository 'http://apt.newrelic.com/debian newrelic InRelease' is no longer signed.
```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Ubuntu 22.04.5 LTS

## Additional context

[TIP]:  # ( Add any other context about the problem here. )
