### ISSUE TITLE
PHP 8.1: ALERT: oops, unknown child (88) exited with code 0.

### ISSUE THREAD

**Issue by everythings-gonna-be-alright** [newrelic/newrelic-php-agent#483]
When PHP container start with newrelic extension, FPM write to log this warning:
`ALERT: oops, unknown child (88) exited with code 0. Please open a bug report (https://github.com/php/php-src/issues).`
It appeared after migration to 8.1, can't reproduce this with PHP 7.4

Newrelic agent: v9.20.0 - v10.0.0
PHP 8.1.7
OS: Alpine 3.6
PHP Framework: without framework

**Comment by everythings-gonna-be-alright** [comment]
My bad

**Comment by everythings-gonna-be-alright** [comment]
I don't know why exactly but it happen because of kubernetes `postStart` command in combination with enabled new-relic extension:

```
          lifecycle:
            preStop:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "php ./exec App/Lib/Tasks/Config/ConfigCache" ]
```

**Comment by everythings-gonna-be-alright** [comment]
Temporary solution:
```
          # Fix for ALERT: oops, unknown child (88) exited with code 0 ( lifecycle postStart + newrelic ext )
          command: [ "/bin/sh", "-c", "sleep 0.5 && php-fpm -R -F" ]
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "./exec App/Lib/Tasks/Config/ConfigCache" ]
```
