### ISSUE TITLE
When multiple Appnames are set through newrelic_set_appname() only the first one receives exception stack traces through newrelic_notice_error()

### ISSUE THREAD

**Issue by heldchen** [newrelic/newrelic-php-agent#532]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

in our setup we have an application that is contained of multiple parts, f.e. a backend, a frontend, an api site etc.. to not only have per-site metrics we configured the app names to include two identifierts, one for the entire project and one specific to the corresponding part in `newrelic_set_appname`. example: `newrelic_set_appname('project;frontend');`.

while all the application names are successfully receiving metrics, errors and exceptions that way, unfortunately only the first of the list of app names is also receiving stack traces of exceptions.

## Steps to Reproduce

1. setup the latest newrelic php agent in the default way
2. in the php code at the start of the execution, run `newrelic_set_appname('first;second');`
3. in any piece of the code, send an Exception/Throwable object `newrelic_notice_error($ex);`
4. observe that while both apps will get the error reported, only the app `first` will have the full stack trace of the exception attached to the error

## Expected Behavior

all applications where an error is reported to should contain the stack trace.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

```Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
```
newrelic-php5:
  Installed: 10.0.0.312
  Candidate: 10.0.0.312
newrelic-php5-common:
  Installed: 10.0.0.312
  Candidate: 10.0.0.312
newrelic-daemon:
  Installed: 10.0.0.312
  Candidate: 10.0.0.312
```
